import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import { Suspense } from "react";
import { createClient } from "@/lib/supabase/server";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Nav() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <nav className="bg-white border-b border-gray-200 px-4 py-3">
      <div className="max-w-5xl mx-auto flex items-center justify-between">
        <Link href="/" className="font-bold text-lg text-blue-600">매치블로그</Link>
        <div className="flex items-center gap-4 text-sm">
          {user ? (
            <>
              <Link href="/mypage" className="text-gray-700 hover:text-blue-600">마이페이지</Link>
              <form action="/api/auth/logout" method="POST">
                <button type="submit" className="text-gray-500 hover:text-red-500">로그아웃</button>
              </form>
            </>
          ) : (
            <Link href="/login" className="text-gray-700 hover:text-blue-600">로그인</Link>
          )}
        </div>
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<nav className="bg-white border-b border-gray-200 px-4 py-3 h-14" />}>
          <Nav />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
